### ISSUE TITLE
[FR] Update module PLS toko dan DC

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#100]
Bismillah, assalamualaikum pak bambang.

Afwan pak saya ada feature request lagi. Kita lagi ingin monitoring apakah toko buat PO ke gudang dengan PLS, nah kita pinginnya agar penggunaan PLS ini bisa di monitor dari gudang. 

jadi tolong dibuat : 

Jika toko buat PO dengan analisa PLS, hasil hitungan saran order juga di export via CSV, yang kemudian di gudang di display juga saran ordernya. Dan di gudang di highlight apakah item PO di order sesuai saran, tidak sesuai saran order, atau tidak pakai PLS sama sekali.
Sehingga staff gudang bisa cek apakah toko betul pakai PLS, atau hanya asal pakai saja.

Dan ini saya ada minta dirubah sedikit behavior waktu buat PO nya : 

Jika user melakukan PO dengan PLS, kemudian user klik mode manual, tolong hasil PLS nya tetap disimpan. Behaviour sekarang jika user melakukan diatas, PO nya dianggap tidak pakai PLS.

Terimakasih pak, jazakallahu khairan

**Comment by AbuMuhammad** [comment]
وَعَلَيْكُمُ السَّلاَمُ وَرَحْمَةُ اللهِ وَبَرَكَاتُهُ

[ PO: Manual tidak menghapus hasil pls ](https://github.com/Ahadmart/ap3/commit/d5196c7e3c532a00468d4a69fe5f5ad3ed240134)
[ PO - csv: Tambahan kolom saran_order ](https://github.com/Ahadmart/ap3/commit/afd9dcb718b328296b5975fcd7b2a4e90b1e04d3)

وَأَنتَ جَزَاكَ اللَّهُ خَيْرًا

**Comment by AbuMuhammad** [comment]
Untuk ahad-dc
[ PO Toko - import: Tambahan untuk kolom saran_order ](https://github.com/Ahadmart/AhadGudang/commit/dfc197ef72df33446226f3a52eaf64ee9073ad0a)
[ Po toko - detail: style untuk beda saran dg order ](https://github.com/Ahadmart/AhadGudang/commit/74246251753a3d0d4e2b6d9a054ad57e6addf203)

**Comment by swawif** [comment]
Saya sudah cek untuk di ahadpos, sudah oke pak alhamdulillah

Untuk ahad-dc.. saya belum lihat style nya kalau pakai style hijau ahadpos2. pas pakai dark theme kelihatan

selain itu ini sudah oke pak, jazakallahu khairan pak
