### ISSUE TITLE
Kolom total di report/kartustok agak geser

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#102]
Bismillah, assalamualaikum pak bambang @AbuMuhammad 
Afwan pak, mau minta tolong, di `report/kartustok` di baris totalnya di paling akhirnya dia ke geser dari baris diatasnya. bisa tolong di perbaiki pak? 

![image](https://github.com/Ahadmart/ap3/assets/35835489/fe35bb03-cfb6-4384-9f0a-41c8b4cab327)

Syukron, wajazakallahu khairan

**Comment by AbuMuhammad** [comment]
InsyaAllah sudah
[Report Kartu Stok: Perbaikan baris Total/Balance](https://github.com/Ahadmart/ap3/commit/7d82819db1d9a39bf3bdaa9fac6ca0d9307b92a3)

**Comment by swawif** [comment]
syukron pak
