### ISSUE TITLE
[FR] Catat setting Analisa PLS dan kirim setting ini ke DC

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#103]
Bismillah, assalamualaikum pak @AbuMuhammad 
Afwan, saya mau FR lagi pak dalam modul analisa PLS

Saya mau minta tolong dibuatkan jika PO dibuat dengan analisa PLS, tolong settingnya ini disimpan di sistem.
(setting yang dimaksud, Range analisa, Order Period, Lead time, Safety stock days, Rak, Struktur)
jadi, setelah di save, saya bisa review ulang PO tersebut. apakah PO ini sudah dibuat dengan setting yang tepat

kemudian, catatan ini juga di kirim di csv ke DC. jadi begitu di import ke sistem ahad-dc, setting ini juga bisa kita review di ahad-dc

syukron wajazakallahu khairan

**Comment by AbuMuhammad** [comment]
Sama dengan yang ini bukan ya?
https://github.com/Ahadmart/ap3/issues/100

**Comment by swawif** [comment]
oh bukan pak. yang saya maksud di catat itu setting ini pak 
![image](https://github.com/Ahadmart/ap3/assets/35835489/f18c1802-4e4a-45d2-847c-771cc65daa3b)

kita pingin tahu apakah staff sudah betul belum dalam setting PLS. karena saat ini kasus yang sering terjadi, staff sudah pakai PLS, tapi gak ikutin saran order. biasanya mereka lebihkan dari saran order. pas saya usut, ternyata karena mereka salah kasih parameter di setting PLS nya

**Comment by AbuMuhammad** [comment]
InsyaAllah sudah, ada tombol tambahan untuk melihat parameter analisa pls
![image](https://github.com/Ahadmart/ap3/assets/3438768/b945cb0e-e946-4028-8970-92f54bf99a62)

**Comment by AbuMuhammad** [comment]
Agar parameter ini bisa dikirim via file. Maka ada fitur tambahan cetak/export ke file Json
![image](https://github.com/Ahadmart/ap3/assets/3438768/0e60c203-6a7c-44fa-8b96-63eaf7e35484)

**Comment by swawif** [comment]
afwan pak, saya belum lihat ini di semua PO ya
Ada apa ya pak?

**Comment by AbuMuhammad** [comment]
> afwan pak, saya belum lihat ini di semua PO ya Ada apa ya pak?

Di toko mana yang belum ada?
