### ISSUE TITLE
[FR] saat SO Jika ada barang beda rak dari settingan rak, di tandai dengan warna

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#104]
Bismillah, assalamualaikum pak bambang.
afwan pak saya mau minta saat SO, kalau ada barang yang rak nya tidak sesuai dengan setting rak di SO saat ini, tolong agar barang ini di tandai dengan warna. jadi kita tahu kalau barang ini salah rak. setelah SO di save, barangnya juga di bawa ke rak barunya, sesuai behaviour sekarang..

syukron, wajazakallahu khairan

**Comment by AbuMuhammad** [comment]
InsyaAllah sudah
![image](https://github.com/Ahadmart/ap3/assets/3438768/d1865965-0cb3-4d53-bf71-0e3e2e6bc7eb)

**Comment by swawif** [comment]
Alhamdulillah syukron pak
