### ISSUE TITLE
[FR] Perubahan behaviour barang non aktif

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#105]
Bismillah, assalamualaikum pak bambang. 

Pak bambang, minta tolong untuk barang non-aktif agar diubah behaviournya. 
sebelumnya barang non-aktif tidak bisa di jual

saya minta barang non-aktif agar di buat tetap bisa dijual, tapi stoknya tidak boleh sampai minus. begitu stoknya 0, barang tersebut tidak bisa dijual lagi.

tujuannya agar toko bisa menandai barang mana saja di stok mereka yang masih ada yang sudah tidak laku lagi. mereka set non-aktif agar barang tersebut modalnya jadi 0, sehingga bisa diskon besar2an agar mempercepat keluar dari toko. dan juga untuk menandai barangnya agar tidak di order kembali.

terimakasih sebelumnya pak, jazakallahu khairan

**Comment by AbuMuhammad** [comment]
![image](https://github.com/Ahadmart/ap3/assets/3438768/a882e352-8989-4613-8f08-cfbae201dbab)

InsyaAllah sudah

**Comment by swawif** [comment]
thayyib jazakallahu khairan pak
