### ISSUE TITLE
[FR] Perubahan behaviour Minimum Restock

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#106]
Bismillah, assalamualaikum pak bambang

afwan pak, ini setelah saya review lagi, sepertinya fitur min restock baiknya kita kembalikan ke behaviour awal saja
Saat ini kan behaviournya dia menambah saran order sesuai jumlah setting min restoknya, tanpa melihat sisa stok barang.

Bisa tolong dikembalikan ke awal, yang dia melihat kondisi ini : 
- Tujuan : Menjaga agar stok toko minimum terjaga minimal sebesar angka minimum restock yang sudah di setting.
- Saat membuat saran order menggunakan Analisa PLS : 
  -  Jika `SO + St < MR` maka `O = MR`
  - Jika `SO + St > MY` maka `O = SO` (tidak dirubah). 
```
SO : Saran Order
St : Stock saat ini 
O : Order total
MR : Minimum Restock yang di set
```

contoh kalau dalam kasus seperti ini, harusnya ordernya jadi 8 (mengikuti MR)
![image](https://github.com/Ahadmart/ap3/assets/35835489/871b03d0-7cee-4bf1-ac3d-c914557fbd87)

tapi dalam kasus ini, harusnya order jadi 185 (mengikuti SO)
![image](https://github.com/Ahadmart/ap3/assets/35835489/f3fb2e93-3dfa-4320-badc-5689c4632c66)

Jazakallahu khairan pak

**Comment by AbuMuhammad** [comment]
InsyaAllah sudah
![image](https://github.com/Ahadmart/ap3/assets/3438768/057c3022-6170-4e1b-93e3-cc8e9fceb495)
Wa anta jazakallahu khoiro

**Comment by swawif** [comment]
Afwan pak, pas saya coba lagi kok kurang pas ya. sepertinya ana juga kurang paham konsepnya mau seperti apa
karena saat ini yang terjadi, ada barang yang stoknya 20, saran ordernya 0
tapi karena ada min restock 5, barang ini jadi di order 5.

kalau seperti ini, artinya tiap kali staff buat PO, barang ini akan di order terus menerus. walaupun saran ordernya tetap 0.

yang saya inginkan, min restock ini ngejaga agar Minimal stok barang itu ada 5.
jadi kalau kasus di atas, dengan stoknya masih 20. seharusnya tidak ada order.
tapi kalau kasusnya barangnya stoknya tinggal 3, tapi saran order tetap 0, harusnya min restock intervensi dan nge set order jadi 2, agar stoknya terjaga di 5

afwan ya pak, semoga bisa di pahami. 
barakallahu fikum

**Comment by swawif** [comment]
alhamdulillah sudah fixed ya
