### ISSUE TITLE
FR : Modifikasi Customer Display

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#109]
Bismillah, assalamualaikum pak bambang.
saat ini kita lagi mau buat tampilan baru di kasir. dan salah satu updatenya, kita mau buat customer display untuk setiap kasir. sekalian ini, saya mau customer display di tambah fungsionalitasnya agar bisa lebih membantu untuk customer kita.

berikut ini desain yang saya buat. mungkin dari pak bambang kalau ada fitur yang agak sulit di implementasi, bisa kita diskusikan baiknya bagaimana

desain dasarnya seperti ini
![image](https://github.com/Ahadmart/ap3/assets/35835489/e676d262-31f7-4f68-a811-0c37c2a57a6d)

Statenya dapat berubah tergantung status transaksi kasir.

![image](https://github.com/Ahadmart/ap3/assets/35835489/903b59b7-3ac7-436e-a1d0-46776c7aa825)

![image](https://github.com/Ahadmart/ap3/assets/35835489/177ec85b-f099-4589-ab6c-51fb2b3b26b1)

![image](https://github.com/Ahadmart/ap3/assets/35835489/1d535862-196a-4af5-96a2-17df8c921783)

![image](https://github.com/Ahadmart/ap3/assets/35835489/cf2cc51d-b84f-49e3-9966-474cd1ea108a)

![image](https://github.com/Ahadmart/ap3/assets/35835489/20fad591-eab2-48f1-9e34-b6e51b5253b5)

bagaimana pak? apa memungkinkan kita buat seperti ini?

syukron, wajazakallahu khairan

**Comment by AbuMuhammad** [comment]
![AhadPOS ۳ - Desktop Customerdisplay - hijau](https://github.com/Ahadmart/ap3/assets/3438768/3e9add15-2964-4b55-8d36-b59bb39c0337)
![Screenshot 2024-05-21 at 10-55-24 AhadPOS ۳ - Desktop Customerdisplay dark-trx](https://github.com/Ahadmart/ap3/assets/3438768/6dd32031-213a-4752-9d1c-87d86a663134)
![Screenshot 2024-05-21 at 10-56-26 AhadPOS ۳ - Desktop Customerdisplay tariktunai orange](https://github.com/Ahadmart/ap3/assets/3438768/d45def85-2900-4d84-ab9f-b1661afc3b67)

![Screenshot 2024-05-21 at 10-57-44 AhadPOS ۳ - Desktop Customerdisplay checkout blue](https://github.com/Ahadmart/ap3/assets/3438768/b5a7dc0c-3dd8-416f-85bb-59b71eb820a8)

**Comment by swawif** [comment]
Alhamdulillah, jazakallahu khairan pak

**Comment by masrebo** [comment]
Mhn maaf ingin bertanya pak, apakah perubahan pada customer display ini sdh terupdate pada repo ahadpos? Soalnya repo terakhir yg sy gunakan, customer display hanya menampilkan total harga belanja saja, tidak muncul rincian belanja tiap item seperti yg terlampir pada gambar di atas. Ataukah ada pengaturan khusus agar bisa sprt gambar di atas tampilannya? Jazakallahu khairan
