### ISSUE TITLE
FR : Modifikasi modul Input Stock Opname

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#110]
Bismillah, assalamualaikum pak bambang.
kemarin setelah SO di toko, saya rasa ada perlu perubahan di modul Input SO

1. di input SO via scan barcode, perlu ada tombol untuk memindahkan rak dan menon-aktifkan barang
yang saya tahu selama ini kalau dari modul SO kita mau pindah rak atau non aktifkan barang, kita harus pakai mode manual.
tapi saat ini kita lebih sering pakai mode normal.
tapi kita tetap perlu untuk bisa memindahkan rak dan non-aktifkan barang saat SO. jadi tolong di tambahkan dropdown dan checklistnya (seperti di gambar di bawah)

PC : 
![image](https://github.com/Ahadmart/ap3/assets/35835489/c01a2f42-2512-4a6d-bcbb-ce9292674db1)

Mobile : 
![image](https://github.com/Ahadmart/ap3/assets/35835489/5aca2272-75c7-46a9-adb2-a3835e2c95a7)

yang saya ingat dari mode manual, kalau kita pindah rak, atau non aktifkan barang, eksekusi dilakukan saat itu juga.
harusnya eksekusinya baru dilakukan setelah user save inputan. jadi jika user salah pencet, perubahan masih bisa dibatalkan

dan saya minta di list barang SO di buat seperti ini. kalau ada pemindahan rak / non-aktif
![image](https://github.com/Ahadmart/ap3/assets/35835489/79f39ca1-2330-4950-8cf7-0bfd07835cae)

setelah SO di save, list ini juga tetap ada. jadi kita bisa review kembali barang apa saja yang di pindahkan dan di non-aktifkan

2. Tampilkan barcode di mobile display
Belakangan ini kita jadi lebih banyak pakai HP untuk SO di toko. cuman kekurangannya di HP. barcode tidak muncul
minta tolong di tampilkan pak. mungkin bisa di buat seperti ini, kalau tidak cukup spacenya 
![image](https://github.com/Ahadmart/ap3/assets/35835489/33bbe8ca-fbf2-43ed-b7a6-37c7607859a1)

dan juga untuk mode manual, bisa dibuat barcodenya tetap muncul juga?
kadang yang saya lihat, barcodenya kadang ada, kadang tidak ada. saya perlu putar hape dari potrait ke landscape dulu biar muncul.
dan biasanya kalau saya ada input SO di mode manual, nanti kolom barcode itu juga hilang

jazakallahu khairan pak

**Comment by AbuMuhammad** [comment]
![image](https://github.com/user-attachments/assets/6a7e0217-9748-46d3-844f-92e1232bd7a5)
![image](https://github.com/user-attachments/assets/6f166504-7455-4e80-8ac5-bab219380918)
insyaAllah sudah

**Comment by swawif** [comment]
Alhamdulillah, jazakallahu khairan pak
