### ISSUE TITLE
FR : ubah behaviour cetak form SO dengan opsi "Barang aktif saja"

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#111]
Bismillah, assalamualaikum pak bambang
saat ini, jika opsi "Barang aktif saja" di pilih, semua barang non-aktif kan tidak muncul
bisa tidak pak di rubah, jika ada barang non-aktif tapi stoknya tidak 0 (termasuk minus), dia di munculkan juga (tapi namanya di tambah <NA> dibelakangnya?

karena yang saya rasa, kemarin setelah SO, takutnya ada barang non-aktif yang dia masih ada stoknya di komputer. tapi fisiknya sudah tidak ada
tapi karena di form juga tidak muncul, akhirnya barang ini tidak pernah di koreksi.

jazakallahu khairan pak

**Comment by AbuMuhammad** [comment]
![image](https://github.com/user-attachments/assets/47d2049d-4eb4-46f3-84d5-ba4edc7c9009)
Bisakah dengan men_disable_ pilihan [barang aktif saja] dan [kecuali stok 0]? Sehingga seperti di bawah ini

![image](https://github.com/user-attachments/assets/18e4ed58-d9ba-4896-8275-dc6950aa40f9)
Agar barang tidak aktif dan stoknya 0 muncul. 

Jadi mungkin nanti tinggal ditambahkan "tanda" untuk barang tidak aktif di formnya

**Comment by AbuMuhammad** [comment]
![image](https://github.com/user-attachments/assets/7d807b1e-6bd8-4c2d-8942-62da85a3c946)
Sudah ditambahkan tanda untuk barang tidak aktif yang diprint di Form SO

**Comment by swawif** [comment]
Alhamdulilah, jazakallahu khairan sudah di tambah tanda nya pak

mungkin kalau tidak, switch [barang aktif saja] default statenya non aktif pak.
jazakallahu khairan
