### ISSUE TITLE
Rincian Belanja di Customer Display

### ISSUE THREAD

**Issue by masrebo** [Ahadmart/ap3#117]
Assalamu'alaykum warahmatullah wabarakatuh, 

Tampilan customer display cmn muncul total harga belanja saja, tdk ada rincian belanja. 
Sebelumnya sy download file² yg ada di branch "master", apa harus pake file² yg ada di branch "feature/customerdisplay2" yah agar tampilan customerdisplay ada perubahan? Mhn maaf sy awam dgn github.

**Comment by AbuMuhammad** [comment]
Silahkan download branch develop.
Customer Display desktop memakai websocket untuk mengupdate tampilannya. 
Server scriptnya ada di `protected/ws/ws_server.php`

Untuk linux systemd bisa dicopy (diedit/disesuaikan dahulu path yang diperlukan) file `protected/ws/ahadpos-websocket.service `ke `/etc/systemd/system` dan kemudian dienable servicenya agar otomatis jalan ketika komputer up (`sudo systemctl enable ahadpos-websocket.service`).

Kemudian di aplikasi. Enable config "customerdisplay.pos.enable" yang ada di menu Config->Aplikasi->Config

**Comment by masrebo** [comment]
Alhamdulillah sdh berhasil setelah pake php 8.x
Maaf pak mau tanya satu lagi, setiap ada update berikutnya, apakah sy downloadnya yg di branch "develop" itu yah?
Jazakallahu khairan telah banyak membantu kami pak

**Comment by AbuMuhammad** [comment]
Ya, insyaAllah branch develop adalah yang terupdate dan bisa dipakai di produksi. Jadi, silahkan ambil dari sana.
Sekali-sekali saya update branch master. Jadi branch master adalah branch yang stabil, tapi belum terkini.
Untuk php, saat ini ahadpos3 stabil di php 8.2.
Wa anta jazakallahu khoiro
