### ISSUE TITLE
Format File CSV Transaksi Pembelian

### ISSUE THREAD

**Issue by masrebo** [Ahadmart/ap3#118]
Assalamu'alaykum warahmatullah wabarakatuh, 

Mhn petunjuknya, dimana/bagaimana bisa mendapatkan/generate file CSV utk import data pembelian (transaksi pembelian), sehingga proses input data pembelian jadi lebih cepat. 

Jazakallahu khairan

**Comment by AbuMuhammad** [comment]
Silahkan lihat di `protected/models/UploadCsvPembelianForm::simpanCsvKePembelian()`

**Comment by masrebo** [comment]
sy sdh coba generate file CSV lewat menu Penjualan spy seakan-akan file tsb digenerata oleh bagian gudang/supplier, dan hasilnya seperti yg tertera pada issue #79 

setelah upload, tidak ada pesan apa-apa, namun data gagal dimasukkan. nah kemudia sy coba telusuri lewat pesal log Yii (**runtime/application.log**)saat melakukan upload, muncul pesan log berikut.


2024/12/20 04:01:04 [info] [application] Checksum: c14bb253778466289d59e48aa654cd3b42ee48c529c338600cb8fe9ba243ecec
in /opt/lampp/htdocs/ahadpos/protected/models/UploadCsvPembelianForm.php (52)
in /opt/lampp/htdocs/ahadpos/protected/controllers/PembelianController.php (595)
in /opt/lampp/htdocs/ahadpos/index.php (13)
2024/12/20 04:01:04 [info] [application] Import pembelian: Checksum OK, commit transaction
in /opt/lampp/htdocs/ahadpos/protected/models/UploadCsvPembelianForm.php (82)
in /opt/lampp/htdocs/ahadpos/protected/controllers/PembelianController.php (595)
in /opt/lampp/htdocs/ahadpos/index.php (13)
**2024/12/20 04:01:04 [info] [application] a:2:{s:6:"sukses";b:0;s:5:"error";a:2:{s:3:"msg";s:98:"Gagal simpan detail pembeliana:1:{s:10:"harga_jual";a:1:{i:0;s:27:"Harga Jual cannot be blank.";}}";s:4:"code";i:500;}}**
in /opt/lampp/htdocs/ahadpos/protected/controllers/PembelianController.php (600)
in /opt/lampp/htdocs/ahadpos/index.php (13)


jika fokus ke baris log ini :
**2024/12/20 04:01:04 [info] [application] a:2:{s:6:"sukses";b:0;s:5:"error";a:2:{s:3:"msg";s:98:"Gagal simpan detail pembeliana:1:{s:10:"harga_jual";a:1:{i:0;s:27:"Harga Jual cannot be blank.";}}";s:4:"code";i:500;}}**

artinya gagal karena harga jual dianggap kosong, tapi sy cek kembali file CSV-nya harga jual tertera.

barcode,idBarang,namaBarang,jumBarang,hargaBeli,hargaJual,RRP,SatuanBarang,KategoriBarang,Supplier,kasir,struktur_lv1,struktur_lv2,struktur_lv3
80000000001,1,"BIMOLI BTL 1 LITER",10,,45800.00,,pcs,makanan,"Toko Mart",admin,"Level 1","Level 2","Level 3"

mohon petunjuk selanjutnya, Jazakallahu khairan

**Comment by masrebo** [comment]
Alhamdulillah ketemu asbab masalahnya, 

Ada kekeliruan dipembacaan posisi kolom terhadap data di CSV pada file "**UploadCsvPembelianForm.php**" di baris **309** dan **310**, **posisi yg tepat** harusnya pada **index ke-4** (hargaBeli) dan **index ke-5** (hargaJual), sehingga solusinya mengubah baris berikut:

` **$detail->harga_beli   = $line[5];
  $detail->harga_jual   = $line[6];**`

Menjadi:

` **$detail->harga_beli   = $line[4];
  $detail->harga_jual   = $line[5];**`

jadi sebelumnya harga_jual dianggap blank sehingga error karena yg terbaca adalah **index ke-6** yaitu kolom "**RRP**" yg memang kosong.

**Comment by masrebo** [comment]
Perlu juga ditambahkan agar bisa melampirkan kolom "expire date" utk setiap barang yg diinput via file CSV.

**Comment by AbuMuhammad** [comment]
> Perlu juga ditambahkan agar bisa melampirkan kolom "expire date" utk setiap barang yg diinput via file CSV. 

Karena ini open source. Jadi ini bisa di"fork", kemudian bebas untuk diubah/disesuaikan/tambah fitur yang sesuai kebutuhan/keinginan.
Silahkan difork ya. Yassarallah
