### ISSUE TITLE
FR: tags

### ISSUE THREAD

**Issue by sufehmi** [Ahadmart/ap3#37]
Dengan fitur tag, maka kita bisa kategorikan barang dengan lebih akurat.

Contoh : boneka bayi bisa di tag "mainan", "bayi", dan "boneka"

**Comment by AbuMuhammad** [comment]
Sudah pernah diminta, dan sudah selesai (closed).

[github.com/Ahadmart/ap3/issues/19](https://github.com/Ahadmart/ap3/issues/19)
