### ISSUE TITLE
Error exception : kategori yang sama

### ISSUE THREAD

**Issue by sufehmi** [Ahadmart/ap3#38]
Jika input kategori dan ada kategori yang sama, 

tangkap errornya, munculkan pesan error / penjelasan.

Saat ini muncul error sbb : 

![dcbee16a-5f1b-4f83-a00c-e7099ec959ea](https://user-images.githubusercontent.com/170206/35950019-0373b130-0ca7-11e8-8d22-9df73aa1ed9d.jpeg)

Terimakasih.

**Comment by AbuMuhammad** [comment]
Tampil seperti itu karena mode Dev (DEBUG), jika diubah ke mode Production, tampilannya lebih _cantik_.
Berikut screenshotnya
![screenshot_20180208_112247](https://user-images.githubusercontent.com/3438768/35955591-dc9bb820-0cc2-11e8-89ac-fa7aad1fa982.png)
Cara ubah mode ada di file index.php
// remove the following lines when in production mode
![screenshot_20180208_112336](https://user-images.githubusercontent.com/3438768/35955603-08ca78b4-0cc3-11e8-97c1-d4aad81ee1de.png)

Error di atas bukan error di aplikasi tapi error di database, jadi tidak bisa saya definisikan (translate) semua errornya. Pesan error mysql dalam bahasa indonesia belum ada.
 
Dengan Bahasa Prancis
![image](https://user-images.githubusercontent.com/3438768/35955909-fada6528-0cc4-11e8-9fb7-112dd3c41a4b.png)

Dalam Bahasa Jepang
![image](https://user-images.githubusercontent.com/3438768/35956023-ae2b0a4c-0cc5-11e8-932b-237e48a9d717.png)

*Toko yang bersangkutan sudah diubah mode nya ke Production
