### ISSUE TITLE
Automatic Cash Drawer

### ISSUE THREAD

**Issue by sufehmi** [Ahadmart/ap3#40]
Saya sedang membeli sebuah Cash Drawer, yang kemudian bisa disambungkan ke printer Epson, sehingga bisa dibuka dari AhadPOS 3 dengan mengirimkan control code Epson, sbb : 

http://www.beaglehardware.com/howtoprogramcashdrawer.html

Mohon agar setelah cetak struk, kemudian mengirimkan control code tsb ke printer, 
sehingga cash drawer (jika ada) akan terbuka otomatis

Terimakasih

**Comment by sufehmi** [comment]
Daftar control code untuk buka cash drawer dari berbagai printer, cukup lengkap : 

http://keyhut.com/popopen4.htm

**Comment by AbuMuhammad** [comment]
Sudah ada pak.
AhadPOS٣ sudah bisa "auto kick" cash drawer

**Comment by AbuMuhammad** [comment]
Bisa disetting di Config - Devices (yang tipenya Printer LPR)
Ada LF (Line Feed) (tambahan baris kosong sebelum dan/atau setelah print struk)
Auto Cutter (Untuk printer yang ada cutter nya)
Auto Kick (Jika ada cash drawer yang terhubung ke printer lpr tersebut)

![screenshot_20180222_115049](https://user-images.githubusercontent.com/3438768/36520954-b05756c0-17c6-11e8-993f-49c708044abf.png)
