### ISSUE TITLE
Revisi modul PO

### ISSUE THREAD

**Issue by sufehmi** [Ahadmart/ap3#42]
Mohon agar bisa di revisi sbb : 

1. Limit Estimasi Sisa Hari : jika hover, muncul penjelasan "Hitung jumlah stok yang musti dipesan untuk ketersediaan dalam jangka waktu ini"

2. Range Analisa Penjualan : jika hover, muncul penjelasan "Lakukan analisa penjualan barang selama berapa hari yang lalu"

3. Kolom Ads : jika hover, muncul penjelasan "Average Daily Sales"

4. Kolom Est Sisa Hari : jika hover, muncul penjelasan "Stok saat ini masih bisa bertahan selama berapa hari"

5. Ada dropdown untuk pilih berapa banyak record yang dimunculkan dalam 1 halaman : 20, 50, 100, Semua

6. Nampaknya analisa PLS ini ke semua stok, tidak hanya ke supplier ybs ? Jika ya, mohon agar bisa dibatasi untuk supplier ybs saja.

Terimakasih.

**Comment by AbuMuhammad** [comment]
Selesai
[2e2d9aa855ef6d5baf044fa4cbc7cf8d81baf3ab](https://github.com/Ahadmart/ap3/commit/2e2d9aa855ef6d5baf044fa4cbc7cf8d81baf3ab)
