### ISSUE TITLE
pembelian, tidak muncul pilihan profil

### ISSUE THREAD

**Issue by goparklubanic** [Ahadmart/ap3#44]
Assalamu 'alaikum wr wb.
Versi AP: 3.0

Trouble:
Tidak bisa menambah data pembelian. Field Profil yang harusnya berisi profil supplier dll, tidak menampilkan data profil yang suda diisikan lewat menu config->profil.

Mohon periksa dan solusi. Sistem digunakan oleh Gerai 212 Mart Banjarnegara

**Comment by AbuMuhammad** [comment]
Wa 'alaikum salam.
Jika ini baru, silahkan ulangi proses install database. Karena sepertinya ada script installasi yang tidak tereksekusi. Mungkin ada bug di versi mysql tertentu.. idk

Tapi jika sudah ada data nya. silahkan jalankan sql di bawah ini
`ALTER TABLE `profil` AUTO_INCREMENT = 101`

**Comment by goparklubanic** [comment]
note:
versi mysql: mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
OS Debian dan Windows
versi php: PHP 7.0.30-0+deb9u1 (cli) (built: Jun 14 2018 13:50:25) ( NTS )

**Comment by goparklubanic** [comment]
Done. Install ulang
