### ISSUE TITLE
Penunjukan waktu salah di resi

### ISSUE THREAD

**Issue by dnbetatester** [Ahadmart/ap3#45]
saat mencetak resi format waktu yang ditunjukan jauh berbeda dari waktu realtime.
kelewat 6 jam

**Comment by AbuMuhammad** [comment]
resi apa?

**Comment by AbuMuhammad** [comment]
Coba cek dan set timezone di php.ini

`date.timezone = "Asia/Jakarta"`

list timezone lainnya bisa dilihat di [sini](http://php.net/manual/en/timezones.asia.php)
