### ISSUE TITLE
Tidak Bisa Cetak Struk Setelah Klik Simpan

### ISSUE THREAD

**Issue by naguibsulaimana** [Ahadmart/ap3#47]
Saya melakukan transaksi penjualan dihalaman POS=>new. Setelah klik simpan, struk tidak tercetak, yang muncul adalah pop up kosong. Solusinya bagaimana?
Catatan: sya menggunakan xampp di windows 7

**Comment by AbuMuhammad** [comment]
Untuk windows, saat ini bisa memakai jenis printer "Printer - Browser" (Konfigurasi ada di menu Config -> Devices).
Untuk tambahan informasi, bisa dilihat pembahasan di [https://github.com/Ahadmart/ap3/issues/24](https://github.com/Ahadmart/ap3/issues/24)
