### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by abuarsyad** [Ahadmart/ap3#51]
mohon maaf jika sudah ada issue yang seperti saya tanyakan. dan mohon bantuannya, ketika selesai proses instalasi kemudian mencoba membuka halaman log in. terjadi kesalahan dan muncul error 404 not found.
saya sudah mengaktifkan mod_rewrite, namun error masih muncul
terima kasih atas jawabannya

**Comment by AbuMuhammad** [comment]
Bisa dibantu dulu lengkapi infonya?
1. Pakai windows/linux?
2. Path directory ahadpos3?
3. Alamat url untuk mengakses ahadpos3?
