### ISSUE TITLE
Tidak bisa masuk "Mode Admin" pada jendela POS Kasir

### ISSUE THREAD

**Issue by faztrain** [Ahadmart/ap3#55]
Mhn bantuannya rekans,
Pembatalan transaksi di jendela POS Kasir hanya bisa dilakukan oleh "admin", nah sy sdh coba masuk "mode admin", tp koq tidak bisa yah? padahal user dan password admin sdh benar dan mengklik tanda centang. Tombol yg bertuliskan "mode admin" terus-terusan berwarna merah kedap kedip dan tidak bisa masuk mode admin sehingga pembatalan transaksi tdk bisa dilakukan.
Mhn solusinya, Terima kasih...

**Comment by AbuMuhammad** [comment]
Ada settingan di protected/config/main.php

`'useradmin' => 'SUPERVISOR'`

Ini bisa diganti dengan ADMIN, atau siapkan user dengan role SUPERVISOR

**Comment by faztrain** [comment]
Alhamdulillah, terima kasih bnyk pak :)
