### ISSUE TITLE
[Solved] Solusi cetak langsung di POS Print pada Client Windows

### ISSUE THREAD

**Issue by faztrain** [Ahadmart/ap3#56]
Sekedar info buat rekans,
Sy menggunakan ahadPOS yg diakses dari client Windows dan bisa nyetak langsung ke POS Printer tanpa mengubah komposisi coding pada ahadPOS, tetap via LPR Linux.
.
Yg sy lakukan adalah sbb:
1. ahadPOS tetap terpasang pada mesin Linux (Server), karena ahadPOS menggunakan LPR utk mengirimkan perintah cetak ke POS Printer.
.
2. Pada client Windows yg mengakses ahadPOS diaktifkan fitur LPD Print Service agar terbuka layanan menerima perintah cetak dari jaringan.
.
3. Karena LPR Linux (Server) tidak kompatibel dengan LPD Print Service Windows, maka pada Linux sy tambahkan CUPS, dan kayaknya pada client Linux pun CUPS ini wajib diinstall agar bisa menerima perintah cetak dari LPR.
.
4. CUPS pada Linux (Server) sy tambahkan koneksi printer baru dengan mode LPD agar nantinya CUPS dapat terhubung ke LPD Print Service Windows.
.
5. Secara ringkas alur komunikasi yg terjadi adalah dari LPR Linux kirim perintah cetak ke CUPS Linux pada mesin yg sama, lalu kemudian CUPS Linux meneruskan perintah cetak tsb ke LPD Print Service Windows, dan terakhir LPD Print Service Windows meneruskan perintah cetak tsb ke POS Printer yg terhubung di client Windows.
.
Alurnya nampak cukup panjang, namun berhasil :)
Moga membantu rekans...

**Comment by AbuMuhammad** [comment]
Terima kasih atas kontribusinya

**Comment by sufehmi** [comment]
Terimakasih, ini sudah saya pin, agar bisa makin bermanfaat untuk yang lainnya juga.
