### ISSUE TITLE
Tidak bisa "Ubah" dan "Hapus" Profil dgn nilai "id" di bawah 101

### ISSUE THREAD

**Issue by faztrain** [Ahadmart/ap3#57]
Mhn pencerahannya rekans,
Setelah sy buat profil "Supplier" lalu kemudian hendak "mengubah" atau "menghapus" ternyata tidak bisa, muncul pesan "Profil ini tidak boleh diubah" dan "Profil ini tidak boleh dihapus".

Lalu sy kemudian coba ubah id supplier menjadi 101 ke atas, ternyata bisa. sy cek file "protected/controllers/ProfilController.php" ternyata ada baris berikut ini:

if ($id >= 101) {
            $model = $this->loadModel($id);
        } else {
            throw new CHttpException(500, "Profil ini tidak boleh diubah");
        }

if ($id >= 101) {
            $this->loadModel($id)->delete();
        } else {
            throw new CHttpException(500, "Profil tidak boleh dihapus!");
        }

Masalahnya hal ini entah mengapa berdampak saat akan nambah barang di menu "pembelian", nama profil supplier yg telah ditambahkan tidak muncul dalam pilihan sehingga proses tambah pembelian gagal dilakukan.
.
Mhn petunjuknya rekans, terima kasih bnyk :)

**Comment by AbuMuhammad** [comment]
Sudah pernah dibahas di sini [https://github.com/Ahadmart/ap3/issues/44](https://github.com/Ahadmart/ap3/issues/44)
