### ISSUE TITLE
Mengubah ukuran cetak huruf pada struk

### ISSUE THREAD

**Issue by faztrain** [Ahadmart/ap3#58]
Assalamu'alaykum, mohon pencerahannya rekans.
Sy ingin agar ukuran cetak huruf di POS Printer bisa dikecilkan agar di kertas bisa muat dan rapi, sy menggunakan Printer dan Kertas Struk ukuran 58x40. Apa yg harus sy konfigurasi? Apakah ada fiturnya di AhadPOS ataukah musti mengubah koding-nya? Terima kasih banyak.

**Comment by AbuMuhammad** [comment]
Tidak ada konfigurasinya. Silahkan pelajari: ESC/POS, a proprietary EPSON POS printer command system

**Comment by faztrain** [comment]
Alhamdulillah sdh bisa pak, sy ngedit file pejualan dan kasir, biar hasil cetaknya muat dan rapi dgn printer yg sy gunakan.
