### ISSUE TITLE
Implementasi AP3 secara internet

### ISSUE THREAD

**Issue by Amadaus684** [Ahadmart/ap3#59]
Implementation dari AP3 disarankan melalui local atau intranet. Nah kalau secara online atau internet, bisa tidak? Khususnya ketika menggunakan fitur printing. Karena saya coba dengan AP3 ada di server online, untuk ngeprint nya masih belum bisa.

**Comment by myzahron** [comment]
Kalau menurut saya bisa sih, untuk nge-print menggunakan pilihan "printer
browser"

**Comment by AbuMuhammad** [comment]
Kalau pertanyaan bisa atau tidak? Jawabannya bisa. Karena ini aplikasi berbasis web. 

Masalahnya adalah koneksinya. 
Untuk printer via lpd/lpr bisa disambungkan oleh "orang network", sehingga printer di **client bisa diakses oleh server**. Hint: bisa via vpn sendiri atau forward port dengan ddns. 
Atau bisa memanfaatkan pilihan fitur printer browser (ini belum pernah kami coba, silahkan dicoba sendiri dan diubah sendiri jika perlu), yang ada di pilihan device

**Comment by AbuMuhammad** [comment]
Barusan diupdate code dari https://github.com/myzahron. Silahkan diupdate ahadpos3 nya

**Comment by Amadaus684** [comment]
Untuk print menggunakan browser, bisa. Tapi muncul kendala adalah pada seting kertas nya. Hanya ada ukuran A4. Kalau di aplikasi lain (PPOB misal) , ada seting kertas printer.

Jadi ketika kita pilih itu, pertama muncul hanya full tulisan panjang 1 paragraphs. Kemudian kalau di print (karena ukuran print adalah maksimal 86 mm dan seting kertas hanya A4), maka hasil print nya terpotong.

Itu yang saya coba.

**Comment by AbuMuhammad** [comment]
> Jadi ketika kita pilih itu, pertama muncul hanya full tulisan panjang 1 paragraphs. Kemudian kalau di print (karena ukuran print adalah maksimal 86 mm dan seting kertas hanya A4), maka hasil print nya terpotong.

Silahkan diupdate ahadpos3 nya
