### ISSUE TITLE
Error 404 Not Found

### ISSUE THREAD

**Issue by Magungtril** [Ahadmart/ap3#60]
Assalamualaikum,

Sy melakukan instalasi AhadPos di OS Linux Ubuntu 16.04. Sy sudah mengikuti panduan instalasi tetapi ketika sudah selesai dan tes buka halaman login error 404 not found.
Direktori ahadpos3 ada di /var/www/html/ap3/, url ketika coba halaman login localhost/ap3 ketika di enter otomatis masuk ke url localhost/ap3/app/login.
Semua konfigurasi terkait mysql dan apache sudah sy ikuti dari panduan.
Terima kasih atas jawabannya.

**Comment by AbuMuhammad** [comment]
coba jalankan perintah
`sudo a2enmod rewrite; service apache2 restart`

**Comment by Magungtril** [comment]
sudah sy coba hasilnya tetap error 404 not found.

Terima kasih atas jawabannya

**Comment by AbuMuhammad** [comment]
Perintahnya berhasil/gagal?
kemudian perintah ini
`awk '/AllowOverride None/{c+=1}{if(c==3){sub("AllowOverride None","AllowOverride All",$0)};print}' /etc/apache2/apache2.conf > /tmp/nih
cp /tmp/nih /etc/apache2/apache2.conf`
apakah sudah berhasil, ada AllowOverride All di file tersebut?

**Comment by Magungtril** [comment]
sudah sy coba perintah tsb dan sudah berhasil membuka tampilan login. saat ini sudah bisa menggunakan ahadpos3.
terima kasih atas bantuannya,

**Comment by Magungtril** [comment]
Maaf, sy mau tanya jg ahadpos3 bisa menggukan cash drawer merk apapun? Dan utk customer display jg apakah bisa menggunakan pole display LED? 
Terima kasih atas jawabannya.

**Comment by AbuMuhammad** [comment]
Untuk cash drawer, yang ingin dimanfaatkan fungsi "auto kick" nya, adalah yang punya koneksi rj11 ke printer kasir.
Untuk customer display, saat ini bisa baru bisa menggunakan browser (bisa ditampilkan di device lain, semisal smartphone, layar kedua, dll, yang loginnya sama dengan kasirnya). Tidak bisa menggunakan pole display.
