### ISSUE TITLE
file INSTALL.TXT isinya tidak konsisten

### ISSUE THREAD

**Issue by hendysama** [Ahadmart/ap3#61]
tolong bantuannya 

di bagian atas lokasi document root nya ada di /var/www/html/ap3
di bagian bawah lokasinya berubah menjadi  /var/www/ap3
var/www/html/ap3 error
var/www/ap3 juga error

ubuntu 18.04
 php 7.4
 mysql 8.0

jadi server saya setengah jadi ada errornya

`Fresh Install Process..

Droping Database ahadpos3..
Database Dropped!

Creating Database ahadpos3..
Database Created!

Migrating Database..

Yii Migration Tool v1.0 (based on Yii v1.1.23)

CDbException: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /var/www/ap3/framework/db/CDbConnection.php:399
Stack trace:
#0 /var/www/ap3/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /var/www/ap3/framework/db/CDbConnection.php(325): CDbConnection->setActive()
#2 /var/www/ap3/framework/base/CModule.php(394): CDbConnection->init()
#3 /var/www/ap3/framework/cli/commands/MigrateCommand.php(472): CModule->getComponent()
#4 /var/www/ap3/framework/cli/commands/MigrateCommand.php(481): MigrateCommand->getDbConnection()
#5 /var/www/ap3/framework/cli/commands/MigrateCommand.php(512): MigrateCommand->getMigrationHistory()
#6 /var/www/ap3/framework/cli/commands/MigrateCommand.php(84): MigrateCommand->getNewMigrations()
#7 [internal function]: MigrateCommand->actionUp()
#8 /var/www/ap3/framework/console/CConsoleCommand.php(178): ReflectionMethod->invokeArgs()
#9 /var/www/ap3/framework/console/CConsoleCommandRunner.php(71): CConsoleCommand->run()
#10 /var/www/ap3/framework/console/CConsoleApplication.php(92): CConsoleCommandRunner->run()
#11 /var/www/ap3/framework/base/CApplication.php(185): CConsoleApplication->processRequest()
#12 /var/www/ap3/framework/yiic.php(33): CApplication->run()
#13 /var/www/ap3/protected/yiic.php(7): require_once('/var/www/ap3/fr...')
#14 /var/www/ap3/protected/yiic(4): require_once('/var/www/ap3/pr...')
#15 {main}
`

**Comment by AbuMuhammad** [comment]
Untuk ubuntu bisa pakai /var/www/html/ap3

Errornya tidak ada hubungan dengan path di atas.
Di panduan INSTALL.TXT sudah ada:

> # edit install script, make sure the password there for MySQL is correct (mysql -u[user] -p[password])

jadi perintahnya ditambahkan menjadi
`mysql  -u usernya -p paswordnya `
sesuaikan dengan user dan password mysql yang sudah ada
