### ISSUE TITLE
FR : Buat Mobile UI untuk Retur Pembelian

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#63]
Bismillah assalamualaikum pak bambang

bisa tolong untuk menu retur pembelian dibuat Mobile UI nya seperti Menu Penjualan ahad-dc?
[seperti disini ](https://github.com/Ahadmart/AhadGudang/issues/18)

Saya perlu tombol barcode nya sama tablenya saja di buat mobile UInya
selebihnya sudah pas

jazakallahu khairan

**Comment by AbuMuhammad** [comment]
[bf69cef](https://github.com/Ahadmart/ap3/commit/bf69cef95b1523ffad0c75530a12ae05dd979014)
![returbeli mobile](https://user-images.githubusercontent.com/3438768/165457505-7e471316-9a56-43d8-b1ea-bdcb452efc1d.png)

**Comment by swawif** [comment]
alhamdulillah sudah saya test pak,
paling minta tolong kolom ref tidak perlu ada di Mobile-UI
sama apa bisa pak, kalau di mobile-UI setelah tambah barang, textbox Pilih Barang tidak langsung di fokus? soalnya ini bikin keyboard kebuka, dan nutupin list barangnya

jazakallahu khairan pak

**Comment by AbuMuhammad** [comment]
insyaAllah sudah
[829dcb](https://github.com/Ahadmart/ap3/commit/829dcbb6dd7248b77564ac950a96856500354e30)

**Comment by swawif** [comment]
alhamdulillah, jazakumullahu khairan pak 🙏
