### ISSUE TITLE
Retur Beli Status Posted masih bisa export CSV yang bisa di import di Ahad-DC

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#71]
Bismillah pak bambang, tadi saya ketemu barang yang di retur dari Ahad PDKC ke Ahad DC (no dok retur di pdkc 03022206000312)
Saya bingung di Ahad PDKC status retur beli nya masih `Posted`
tapi entah kenapa di Ahad DC returnya sudah di input dan sudah jadi stok nya gudang (no dok retur jual di ahad dc 01042206000643)

selidik2 ternyata staff PDKC saat selesai mem-posted retur beli, dia langsung melakukan cetak CSV, yang dikirim ke Ahad-DC
dan CSV ini saat di import ke Ahad-DC bisa dan dianggap retur yang valid 
(Padahal harusnya tidak, karena fisik barang masih ada di PDKC, jadi kita ada pencatatan dobel di PDKC dan Ahad-DC)

baiknya menurut saya Retur Beli tidak bisa di cetak CSV jika status nya masih `Posted`

jazakallahu khairan pak

**Comment by AbuMuhammad** [comment]
insyaAllah sudah
[3adb09b](https://github.com/Ahadmart/ap3/commit/6cc6f8899734b0cee7f78d7d098658b9c3adb09b)

**Comment by swawif** [comment]
siap jazakallahu khairan pak
