### ISSUE TITLE
Tanggal retur beli di eksekusi mengikuti kapan status berubah jadi posted bukan saat status berubah menjadi piutang

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#72]
Bismillah pak bambang, Berhubungan sama issue #71 (no dok retur pdkc 03022206000312)

saya tadi sempat selidik2 kartu stok dan retur beli nya pdkc, dan saya lihat retur ini di eksekusi pada jam 8.22
padahal saya ngubah statusnya dari `Posted` ke `Piutang` sekitar jam 10.30an

sepertinya itu jamnya nyambung ke saat kapan retur beli nya di Posted, bukan saat barang di keluarkan dari toko / status `Piutang`

bisa dirubah pak behaviournya jadi jam struknya ada dua
- kapan retur di posted
- kapan retur di eksekusi (status piutang)

Untuk yang muncul di kartu stok, mengikuti kapan waktu status berubah jadi piutang

jazakallahu khairan pak, barakallahu fikum

**Comment by AbuMuhammad** [comment]
insyaAllah sudah
[bfdd42c](https://github.com/Ahadmart/ap3/commit/0db29e9df2ab8b631f84c063b1e407795bfdd42c)

**Comment by swawif** [comment]
Naam sudah confirmed yang kartu stok ngikut ke kapan piutang di eksekusi
cuman yang di struk saya belum lihat. cuman saya pikir kayaknya gak terlalu perlu banget

jazakallahu khairan pak
