### ISSUE TITLE
FR: Print Checklist belanja versi Printer Dot Matrix dan versi PDF yg lebih ringkas

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#73]
Bismillah pak bambang

Saya tadi habis diskusi sama tim gudang, dan ternyata selama ini fitur ceklist belanja ini lebih dipakai sama tim pengiriman dalam ngebagi barang kiriman dia
kayaknya perlu dibuat versi dot matrixnya dan pdf yang lebih simple

Untuk yang lebih simple isinya :
- Barcode
- Nama Barang
- Stok barang di Ahad-DC
- Permintaan toko

khusus Dot Matrix, kayaknya dia cuman perlu print yang simpel aja, yang lain gak perlu

jazakallahu khairan pak

**Comment by AbuMuhammad** [comment]
insyaAllah sudah. Dan ini di Ahad DC ya

**Comment by swawif** [comment]
oh iya betul pak, jazakallahu khairan pak 👍
