### ISSUE TITLE
FR: Expor data penjualan per struktur termasuk barang yang tidak memiliki struktur jika opsi struktur di set ke All

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#75]
Bismillah pak bambang

Afwan pak, minta tolong untuk sistem laporan penjualan by struktur. Tolong dibuat jika ada setting tarikan datanya di set All semua, semua penjualan ditarik, termasuk barang yang belum punya struktur.

Barang itu di label dengan `Tidak ada struktur`

Syukron pak

**Comment by AbuMuhammad** [comment]
insyaAllah sudah
[0b0e966](https://github.com/Ahadmart/ap3/commit/4fc5f6eea0144d648c0a388e57cf223b20b0e966)

**Comment by swawif** [comment]
alhamdulillah untuk yg PDF sudah ya pak,
tapi buat yg CSV belum. bisa tolong sekalian juga pak?

**Comment by AbuMuhammad** [comment]
insyaAllah sudah
[a7e9804](https://github.com/Ahadmart/ap3/commit/385f4c727d554936b97327b2e4abc20c7a7e9804)

**Comment by swawif** [comment]
Alhamdulillah jazakillahu khairan pak bambang
