### ISSUE TITLE
FR : Cetak Form SO dan Buat SO Baru perlu ada pilihan untuk barang tanpa rak (NULL)

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#76]
Bismillah pak bambang

tadi saya lihat di sistem SO, gak ada pilihan untuk mencetak Form SO untuk barang yang belum punya rak (NULL)
bisa tolong dibuat opsinya pak sekalian juga di Ahad-DC

karena saat kita input barang, rak tidak wajib di isi.
takutnya banyak barang yang gak bisa kita SO karena gak bisa kita cek data rak nya.

jazakallahu khairan pak

**Comment by AbuMuhammad** [comment]
> takutnya banyak barang yang gak bisa kita SO karena gak bisa kita cek data rak nya.

Ini bisa lewat tools -> edit barang. Pilih rak = NULL. Akan muncul barang-barang yang belum ada raknya. Bisa diedit dulu, untuk diganti raknya. Tujuannya "memaksa" agar setiap barang ada raknya (kalau gak salah ini request juga, dulu..).
Biasanya di toko membuat rak "virtual" yang bernama seperti "rak sementara", dll. Untuk nanti dipindahkan ke rak sebenarnya ketika sudah sempat

**Comment by swawif** [comment]
oh naam pak saya coba itu dulu
tapi kalau gitu minta tolong saat input barang di ahadpos dan ahad-dc, dibuat wajib untuk mengisi rak.
