### ISSUE TITLE
BUG : Buat Penerimaan PO baru loadingnya modulnya sangat lama

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#77]
bismillah pak bambang, 

Tadi saya coba buat PPO baru. ternyata loadingnya sangat lama.
kalau kata staff, ini emang selalu seperti itu

bisa dibuat lebih cepat pak? syukron

**Comment by AbuMuhammad** [comment]
di ahadpos atau ahad-dc?

**Comment by swawif** [comment]
eh maaf ini masalah ahad-dc ya, afwan pak saya pindahkan kesana
