### ISSUE TITLE
FR : Wajib isi Rak dan Struktur saat input pembelian / barang baru

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#78]
Bismillah pak bambang, ini lanjutan dari issue #76 

Baiknya mulai dari sekarang Rak dan Struktur jadi item wajib di input. 
biar gak ada kerancuan dalam data kita

jazakallahu khairan pak

**Comment by AbuMuhammad** [comment]
insyaAllah sudah
[f25f10f](https://github.com/Ahadmart/ap3/commit/f301d4040156d65028e9490dfa2821d22f25f10f)

**Comment by swawif** [comment]
Alhamdulillah jazakallahu khairan pak bambang
