### ISSUE TITLE
Bug / Help needed : AP3 Pd Kacang beberapa kali tidak bisa input pembelian via import dari CSV ahad-dc

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#79]
Bismillah, assalamualaikum pak bambang

afwan pak, kemarin Staff di pd. kacang lapor mereka tidak bisa import csv pembelian dari AhadDC
mereka masuk ke menu pembelian, klik tombol import, pilih profil Gudang.Ahadmart.com, lalu pilih filenya, dan klik upload csv

tapi setelah klik tombol upload csv, tidak ada yang terjadi. page import hanya reload, tanpa error. kembali ke page /pembelian/import/

dan rasanya bukan masalah permission, karena saya coba sendiri dengan user admin saya (syarif), dan tetap tidak bisa

mohon bantuannya pak untuk dicari tahu masalahnya. sementara toko revert ke input manual dulu

penjualan yang bermasalah adalah
- no penjualan DC - 01032207005661 - tgl 6 juli 2022
- no penjualan DC - 01032207005751 - tgl 11 juli 2022

**Comment by AbuMuhammad** [comment]
Pada file-file dari penjualan gudang tersebut di atas, kemungkinan ada barang yang tidak diisi strukturnya oleh gudang. 
Solusi: Minta gudang agar mengisi struktur barang-barang yang belum ada strukturnya, export lagi penjualannya. Di toko import lagi pembelian menggunakan file yang baru tersebut
