### ISSUE TITLE
FR : laporan pembelian detail per nota dan export ke CSV

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#81]
Bismillah assalamualaikum pak bambang

Minta tolong dibuatkan laporan pembelian detail per nota dan export ke CSV nya.
mirip seperti `Penjualan Detail per Nota` tapi untuk pembelian

Untuk CSV nya tolong di buat kolomnya
- Tanggal input
- no ref
- no pembelian toko
- Jumlah pembelian
- profil

Ini karena toko perlu submit ke DC list barang apa saja dari delivery DC yg sudah mereka input. Untuk ngecek apakah ada barang yang terlewat.
Sejauh ini toko ngelakuin nya manual. Tapi ini butuh waktu yang lama. Padahal sekarang jumlah pegawai lagi cukup minim

Jazakallahu khairan pak 🙏

**Comment by AbuMuhammad** [comment]
insyaAllah sudah
