### ISSUE TITLE
Laporan Retur Jual dan Beli

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#82]
Bismillah, Assalamualaikum Pak Bambang

Mau minta tolong buatkan modul untuk di ahadpos dan ahadDC untuk tarik data retur Jual / Beli. 
tolong dibuat ada opsi filter retur
- Periode tanggal 
- Nama Profil Supplier
- Status

Untuk dilaporannya sendiri, tolong di samakan seperti yang di page retur beli dan retur jual.

Syukron, Barakallahu fikum pak

**Comment by AbuMuhammad** [comment]
Wa'alaikumsalam wa rohmatullah.
Untu retur beli, sudah ada laporannya. Apa yang dimaksud berbeda?

**Comment by swawif** [comment]
Subhanallah Afwan pak, kelewat dari saya. Artinya utk retur beli gak perlu pak. Ini cukup insyaa allah

Paling minta tolong ditambah status retur (draft/posted/piutang/lunas/batal)

**Comment by AbuMuhammad** [comment]
insyaAllah laporan retur jual, dan tambahan status untuk laporan retur beli sudah selesai

**Comment by swawif** [comment]
afwan baru lihat lagi pak, naam pak, jazakallahu khairan
