### ISSUE TITLE
Sembunyikan perkiraan Saldo Akhir Kas seharusnya dari modul kasir selama kasir belum ditutup

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#83]
Bismillah, Assalamualaikum Pak Bambang

Afwan, mau minta tolong pak, 
Tolong untuk Saldo Akhir seharusnya di modul kasir/tutup di hapus pak.
Nanti dimunculkannya setelah SPV sudah masukin Saldo Akhir fisik dan kasir sudah ditutup.

Soalnya sering terjadi akhirnya SPV ngisi saldo akhir dengan mencocokan perkiraan AhadPOS.

Syukron, Barakallahu fikum pak

**Comment by AbuMuhammad** [comment]
insyaAllah sudah
[6c345d5](https://github.com/Ahadmart/ap3/commit/455e840499110ee53dc73617c6717186a6c345d5)

**Comment by swawif** [comment]
Afwan pak, ternyata malah kasusnya jadi dicocokkan ke total penerimaan kas...

minta tolong preview nya di hide aja semuanya pak.
Cukup nama kasir, waktu, dan saldo awal saja

Syukron pak

**Comment by AbuMuhammad** [comment]
Sudah diupdate
[Ahadmart/ap3@455e840](https://github.com/Ahadmart/ap3/commit/455e840499110ee53dc73617c6717186a6c345d5)

**Comment by swawif** [comment]
sip jazakallahu khairan pak
