### ISSUE TITLE
Tambah Field User di export report/penjualan

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#84]
Bismillah, Assalamualaikum pak

Afwan mau minta tolong di export report/penjualan, tolong ditambahin field user yang menginput penjualannya
Untuk AhadPOS dan Ahad-DC ya pak

Syukron, barakallahu fikum pak

**Comment by AbuMuhammad** [comment]
InsyaAllah sudah
[Ahadmart/ap3@2482ff1](https://github.com/Ahadmart/ap3/commit/2482ff197cf1d54e7d5148452a9fda61a9b3a8fa)

**Comment by swawif** [comment]
sip pak, jazakallahu khairan
