### ISSUE TITLE
[FR] Modul Laporan Harian Rangkuman

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#85]
Bismillah Assalamualaikum pak bambang

afwan pak, mau minta tolong dibuatkan modul untuk harian AhadPOS dan AhadDC.
Kemarin saya baru tahu dari toko, ternyata mereka selain mencetak harian dari ahadPOS, mereka juga buat harian manual.

usut-usut ini ternyata karena mereka diminta buat harian yang mirip dengan format AbangAdek oleh adminnya abang adek
Jadi mereka terpaksa buat harian dua kali untuk 

berikut ini desainnya pak
https://docs.google.com/spreadsheets/d/1SiEjQZJmmTYK6F6WkJXdhwVkwY4Uopt45E2wIuDOl0A/edit#gid=576592887

Syukron pak

**Comment by AbuMuhammad** [comment]
InsyaAllah sudah selesai, bisa diakses lewat menu Laporan -> Transaksi Harian -> Harian 01

**Comment by swawif** [comment]
Alhamdulillah, barusan sudah saya cek dan sudah cocok
Terimakasih pak, jazakallahu khairan
