### ISSUE TITLE
FR : Hide penjualan saat kasir sedang aktif

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#86]
Bismillah, Assalamualaikum pak bambang, afwan pak, ada feature request lagi

Setelah kemarin saya minta pak bambang untuk hide saldo akhir kasir dari laporan tutup kasir, Ternyata  ada toko yang bisa mengira-ngira saldo akhir itu dengan melihat laporan penjualannya.
ini potensi jadi cara untuk nutupin selisih kasir oleh toko. 

minta tolong dibuat rules di page `penjualan/index` dan semua varian `report/penjualan`
- kalau ada kasir yang aktif, maka penjualan yang terjadi di waktu setelah waktu buka kasir itu di hide, sampai kasir di tutup.
- hanya berlaku untuk user selain admin. Admin tidak kena hide
- jika ada kasir aktif, buat warning diatas laporan / tabel penjualan/index "Sebagian penjualan tidak ditampakkan. Tutup akun kasir yang masih aktif untuk menampakkan seluruh penjualan"

misal, kasir 1 aktif sejak 03/11/2022 11.30, 
kalau user buka page `penjualan/index`, mereka hanya bisa lihat penjualan sebelum jam 11.30 saja
dan kalau user mau buat laporan `report/penjualan` dari 02/11/2022 12.00 s/d 03/11/2022 13.00, semua penjualan antara jam 11.30 - 13.00 tidak dimasukkan. sampai kasir itu ditutup.

mungkin itu pak, kalau ada yang perlu di diskusikan ulang, boleh saja pak
jazakallahu khairan pak 🙏

**Comment by AbuMuhammad** [comment]
Done
