### ISSUE TITLE
FR : Tambahkan cek tanggal di /report/penjualanperstruktur 

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#87]
Bismillah, assalamualaikum pak bambang, 

Afwan pak, untuk di page /report/penjualanperstruktur, bisa tolong dibuatkan cek antara tanggal 'dari' dan 'sampai' 
supaya dipastikan kalau tanggal 'dari' tidak lebih besar dari 'sampai'

syukron, Jazakallahu khairan pak 🙏

**Comment by AbuMuhammad** [comment]
![image](https://user-images.githubusercontent.com/3438768/207504606-e119a6d4-e72f-47e9-8670-0e6ebcaa60cc.png)
InsyaAllah sudah
