### ISSUE TITLE
[FR] Ganti Form daftar member dari minta tanggal lahir jadi minta umur

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#89]
Bismillah assalamualaikum pak bambang

Afwan pak, minta tolong untuk di ganti form daftar member, bagian tanggal lahirnya untuk diganti dari minta tanggal lahir jadi minta umur aja. tapi kemudian umur ini jadi required. 
Tapi kemudian di backend, di convert jadi tanggal
Misal umur dia 20 thn, di backend di catat 01-01-2002

soalnya banyak user yang gak mau ngasih tanggal lahir, karena privasi. tapi kalau umur, insyaa allah lebih bisa. kalau gak bisa juga, staff masih bisa ngira-ngira.

jazakallahu khairan pak

**Comment by AbuMuhammad** [comment]
![image](https://user-images.githubusercontent.com/3438768/209107336-ba970d9e-fa81-4774-9eaa-9d6bdc221e73.png)
InsyaAllah sudah. Wa anta jazakallahu khoiro
