### ISSUE TITLE
[FR] Block akses semua modul harian selama ada kasir aktif

### ISSUE THREAD

**Issue by swawif** [Ahadmart/ap3#91]
Bismillah, assalamualaikum pak bambang

afwan pak, melanjutkan masalah tutup kasir kemarin, bisa minta tolong tutup akses ke modul harian selama ada kasir aktif?
Karena ada beberapa staff yang saat tutup kasir, dia buka modul harian untuk cari tahu omzet dan mengira-ngira saldo akhir kasir

jazakallahu khairan pak

**Comment by AbuMuhammad** [comment]
![image](https://user-images.githubusercontent.com/3438768/208593811-35636b6c-e178-42ee-ae25-4c287c8090a6.png)
insyaAllah sudah. Wa anta jazakallahu khoiro
